site_name: Screwdriver Guide
site_url: http://screwdriver.cd
repo_url: https://github.com/screwdriver-cd/guide
repo_name: GitHub
site_description: All you need to know about Screwdriver and more
# Due to bug in MKDocs: https://github.com/mkdocs/mkdocs/issues/974
# strict: true
theme: yeti
copyright: Yahoo Inc. BSD-3-Clause
extra_css: [css/extra.css, css/yaml.css]
extra_javascript: [js/vendor/jquery-3.1.0.min.js, js/yaml.js]

pages:
    - Home: 'index.md'
    - Getting Started:
        - Set Up a Screwdriver Cluster: 'getting-started/cluster-setup.md'
        - Set Up a Datastore: 'getting-started/datastore-setup.md'
        - Create a Pipeline: 'getting-started/create-pipeline.md'
        - Config File Reference: 'getting-started/yaml.md'
    - Internals:
        - Overall Architecture: 'internals/overall-architecture.md'
        - API: 'internals/api.md'
        - Execution Engines: 'internals/execution-engines.md'
        - Domain Model: 'internals/domain.md'
    - Community:
        - Contributing: 'community/contributing.md'
        - Support: 'community/support.md'
 
