site_name: Screwdriver Guide
site_url: http://screwdriver.cd
repo_url: https://github.com/screwdriver-cd/guide
repo_name: GitHub
site_description: All you need to know about Screwdriver and more
# Due to bug in MKDocs: https://github.com/mkdocs/mkdocs/issues/974
# strict: true
theme_dir: themes/sd
copyright: Â© 2016 Yahoo! Inc. All rights reserved.
extra_css: [css/homepage.css, css/yaml.css]
extra_javascript: [js/vendor/jquery-3.1.0.min.js, js/yaml.js, js/i18n.js]
google_analytics: ['UA-88158708-1', 'docs.screwdriver.cd']

pages:
    - Home: 'index.md'
    - Cluster Management:
        - Overall Architecture: 'cluster-management/index.md'
        - Configuring the API: 'cluster-management/configure-api.md'
        - Configuring the UI: 'cluster-management/configure-ui.md'
        - Configuring the Store: 'cluster-management/configure-store.md'
        - Examples:
            - Kubernetes: 'cluster-management/kubernetes.md'
    - User Guide:
        - Quickstart: 'user-guide/quickstart.md'
        - Authentication and Authorization: 'user-guide/authentication-authorization.md'
        - Configuration:
            - Overall: 'user-guide/configuration/index.md'
            - Secrets: 'user-guide/configuration/secrets.md'
        - API: 'user-guide/api.md'
    - About:
        - Appendix:
            - Domain Model: 'about/appendix/domain.md'
            - Execution Engines: 'about/appendix/execution-engines.md'
        - Contributing: 'about/contributing.md'
        - Support: 'about/support.md'
